name: Kalliergeia
version: '${project.version}'
main: me.adelemphii.kalliergeia.Kalliergeia
api-version: 1.13

commands:
  kalliergeia:
    aliases: k
    # a usage: key would be good here for when the command has a negative return